### ISSUE TITLE
Image delete webservice broken

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/image-service#90]
```
groovy.lang.MissingMethodException: No signature of method: au.org.ala.images.ImageService.scheduleImageDeletion() is applicable for argument types: (au.org.ala.images.Image, java.lang.String) values: [au.org.ala.images.Image : 59587, efd78f89-9e5d-4730-b892-df9d9dec99f3]
Possible solutions: scheduleImageDeletion(long, java.lang.String)
	at au.org.ala.images.WebServiceController.deleteImageService(WebServiceController.groovy:86)
	at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
```

**Comment by djtfmartin** [comment]
This is fixed on the develop branch

**Comment by nickdos** [comment]
Does this need code review?
What is the webservice call to trigger the bug, for testing?

**Comment by djtfmartin** [comment]
thanks @nickdos 

I cant reproduce this now on images-dev.ala.org.au. Im wondering if the elastic search error was a temporary problem after an re-install. There are some index changes on `develop` branch for fixing partial text matches #101 that require a re-index.

Just tested with API keys (whitelist not necessary if api key supplied) and its working as expected.

e.g.

```
 curl -X DELETE https://images-dev.ala.org.au/ws/image/7a5b7964-c87e-4c36-b35c-2891822ced7c -H "apiKey: <INSERT-API_KEY>" 
````

images-dev.ala.org.au is pointing at auth-test - so the API key should be generated on auth-test to be recognised.

I think this can be closed.

**Comment by nickdos** [comment]
FYI, https://github.com/AtlasOfLivingAustralia/image-service/issues/104

Yep, worked when I tested just now, so can close.
